import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{createClient}from"@supabase/supabase-js";
import{CalendarDays,Inbox,LogOut,Mail,Menu,Mic2,Save,Send,Settings2,X}from"lucide-react";
import"../app/globals.css";import"../app/admin.css";import"./overrides.css";

const su=import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY?createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY):null;
const nav=["Portfolio","Foundation","Topics","Highlights","Projects","Contact","RFQ"];

function Header(){const[open,setOpen]=useState(false);const path=location.pathname;return <header className="site-header dark-header"><a className="brand transparent-brand" href="/"><img src="/brand/ariem-logo.png" alt="Ariem Cinco"/></a><nav>{nav.map(x=>{const href=`/${x.toLowerCase()}`;return <a className={path===href?'active':''} key={x} href={href}>{x}</a>})}</nav><a className="btn btn-primary header-cta" href="/schedule">Schedule a call</a><button className="menu-toggle" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button>{open&&<div className="mobile-menu"><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button><span>Navigate</span>{nav.map(x=><a key={x} href={`/${x.toLowerCase()}`}>{x}</a>)}<a className="btn btn-primary" href="/schedule">Schedule a call</a></div>}</header>}
function Footer(){return <footer className="professional-footer"><div className="footer-brand"><img src="/brand/ariem-logo.png" alt="Ariem Cinco"/><p>Communication that moves people.</p></div><div className="footer-links"><strong>Professional links</strong><nav><a href="/portfolio">Portfolio</a><a href="/topics">Speaking topics</a><a href="/contact">Contact</a><a href="/rfq">Request a quotation</a></nav></div><div className="footer-contact"><strong>Connect</strong><a href="mailto:hello@ariemcinco.com"><Mail size={16}/>hello@ariemcinco.com</a><a href="/control-center">Owner control center</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ariem Cinco. All rights reserved.</span><a className="developer-badge" href="https://archieomega.pro" target="_blank" rel="noreferrer"><span>Developed by</span><span className="developer-logo"><img src="/brand/kurama-developer.png" alt="Kurama Information Technology Solutions"/></span><b>KURAMA INFORMATION TECHNOLOGY SOLUTIONS</b></a></div></footer>}
function Shell({children}:{children:React.ReactNode}){return <><Header/><main className="page-main">{children}</main><Footer/></>}
const portfolioSlides=[{tag:'Keynote',title:'Communication That Inspires Action',meta:'Leadership and institutional audiences'},{tag:'Workshop',title:'From Message to Meaning',meta:'Interactive learning experiences'},{tag:'Program',title:'Purposeful Communication',meta:'Custom sessions for organizations'}];
function PortfolioCarousel(){const[active,setActive]=useState(0);useEffect(()=>{const timer=window.setInterval(()=>setActive(v=>(v+1)%portfolioSlides.length),4500);return()=>window.clearInterval(timer)},[]);return <div className="portfolio-carousel" aria-label="Featured portfolio"><div className="carousel-track" style={{transform:`translateX(-${active*100}%)`}}>{portfolioSlides.map((slide,index)=><article className="carousel-slide" key={slide.title} aria-hidden={active!==index}><div><span>{slide.tag}</span><h3>{slide.title}</h3><p>{slide.meta}</p></div><strong>0{index+1}</strong></article>)}</div><div className="carousel-controls">{portfolioSlides.map((slide,index)=><button key={slide.title} className={active===index?'active':''} onClick={()=>setActive(index)} aria-label={`Show ${slide.title}`}/>)}</div></div>}
function Home(){return <><Header/><main><section className="hero"><div className="portrait-wrap"><img className="portrait plain" src="/brand/ariem-portrait.png" alt="Ariem Cinco"/></div><div className="hero-copy"><div className="hero-mark">AC</div><PortfolioCarousel/><p className="eyebrow"><span/>Resource Speaker • Communication Strategist</p><h1>Communication<br/>That Moves People.</h1><p className="lead">Helping leaders, educators, and organizations communicate with clarity, confidence, and purpose.</p><div className="speaker-lockup"><span/><div><strong>Ariem Cinco</strong><small>Resource Speaker</small></div></div><div className="hero-actions"><a className="btn btn-primary" href="/schedule">Schedule a call</a><a className="btn btn-outline" href="/portfolio">View portfolio</a></div></div></section></main><Footer/></>}
const principles=[['01','Listen','Understand the people, context, and real communication challenge.'],['02','Shape','Build a clear message, useful structure, and credible point of view.'],['03','Move','Deliver with confidence and create a meaningful next action.']];
function Portfolio(){return <Shell><section className="section split-section"><div><p className="kicker">Selected work</p><h2>Messages designed to create movement.</h2><PortfolioCarousel/></div><blockquote className="statement framed-quote"><span>“</span>Ariem works with institutions, leaders, and learning communities to shape communication that is human, strategic, and memorable.</blockquote></section><section className="section highlights"><div className="highlight-grid">{['Keynote engagements','Communication workshops','Institutional programs'].map(x=><article key={x}><strong>{x}</strong><p>Purpose-built for the audience and desired outcome.</p></article>)}</div></section></Shell>}
function Foundation(){return <Shell><section className="section foundation page-fill"><div className="section-heading"><p className="kicker">Foundation</p><h2>Clarity first. Purpose always.</h2><p>Every engagement begins with the audience, the outcome, and the message that connects them.</p></div><div className="principles">{principles.map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section></Shell>}
function Topics(){return <Shell><section className="section light-section page-fill"><p className="kicker">Speaking topics</p><h2>Practical ideas, delivered with impact.</h2><div className="topic-grid">{['Strategic Communication','Leadership Communication','Public Speaking'].map(x=><article key={x}><Mic2/><h3>{x}</h3><p>Practical frameworks, memorable insights, and exercises tailored to the audience.</p></article>)}</div></section></Shell>}
function Highlights(){return <Shell><section className="section highlights page-fill"><p className="kicker">Highlights</p><h2>Built for the room, remembered beyond it.</h2><div className="highlight-grid">{['Leaders','Educators','Teams'].map(x=><article key={x}><strong>{x}</strong><p>Communication that creates clarity, confidence, and forward movement.</p></article>)}</div></section></Shell>}
function Projects(){return <Shell><section className="section projects page-fill"><div className="project-feature"><p className="kicker">Projects</p><h2>Talks, workshops, and communication programs.</h2><p>Custom-built sessions for conferences, leadership teams, schools, and institutional events.</p><a className="btn btn-primary" href="/rfq">Request a tailored engagement</a></div></section></Shell>}
function Contact(){return <Shell><section className="section schedule page-fill"><div><p className="kicker">Contact</p><h2>Start a meaningful conversation.</h2><p>For speaking engagements, partnerships, and institutional programs, send an inquiry and the team will respond.</p></div><div className="schedule-card"><Mail/><h3>Speaking engagements</h3><p>hello@ariemcinco.com</p><a className="btn btn-primary" href="mailto:hello@ariemcinco.com">Send email</a></div></section></Shell>}
function RFQ(){const[n,setN]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setN("Sending…");if(!su)return setN("Connect Supabase to activate requests.");const f=e.currentTarget,{error}=await su.from("inquiries").insert(Object.fromEntries(new FormData(f).entries()));if(error)setN(error.message);else{f.reset();setN("Thank you. Your request has been received.")}}return <Shell><section className="section inquiry-section page-fill"><div><p className="kicker">Request for quotation</p><h2>Share your event details.</h2></div><form className="inquiry-form" onSubmit={submit}><label>Full name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Organization<input name="organization"/></label><label>Event type<select name="event_type"><option>Conference keynote</option><option>Workshop</option><option>Leadership session</option><option>School engagement</option></select></label><label>Preferred date<input name="preferred_date" type="date"/></label><label>Audience size<input name="audience_size" type="number"/></label><label className="full">Message<textarea name="message" rows={5} required/></label><button className="btn btn-primary full"><Send size={17}/>Send request</button>{n&&<p className="form-note">{n}</p>}</form></section></Shell>}
function Schedule(){return <Shell><section className="section schedule page-fill"><div><p className="kicker">Schedule a call</p><h2>Let’s plan an engagement that fits your audience.</h2><p>Tell us about your event and preferred schedule through the RFQ form.</p></div><div className="schedule-card"><CalendarDays/><h3>Request a schedule</h3><p>The team will review your preferred date and confirm availability.</p><a className="btn btn-primary" href="/rfq">Continue to RFQ</a></div></section></Shell>}
type I={id:string;name:string;email:string;message:string;status:string;created_at:string};
function Admin(){const[user,setUser]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[note,setNote]=useState(""),[tab,setTab]=useState("content"),[items,setItems]=useState<I[]>([]),[form,setForm]=useState({headline:"Communication That Moves People.",intro:"Helping leaders, educators, and organizations communicate with clarity, confidence, and purpose.",contact_email:"hello@ariemcinco.com",booking_url:""});useEffect(()=>{su?.auth.getUser().then(x=>setUser(x.data.user?.email||null));const s=su?.auth.onAuthStateChange((_e,x)=>setUser(x?.user.email||null));return()=>s?.data.subscription.unsubscribe()},[]);useEffect(()=>{if(user)su?.from("inquiries").select("*").order("created_at",{ascending:false}).then(x=>setItems((x.data||[])as I[]))},[user]);async function login(e:React.FormEvent){e.preventDefault();if(!su)return setNote("Connect Supabase first.");const{error}=await su.auth.signInWithPassword({email,password});if(error)setNote(error.message)}async function save(){if(!su)return;const{error}=await su.from("site_settings").upsert(Object.entries(form).map(([key,value])=>({key,value})));setNote(error?error.message:"Saved successfully.")}if(!user)return <main className="admin-login"><a href="/">← Back</a><form onSubmit={login}><div className="admin-logo">AC</div><p className="kicker">Owner access</p><h1>Control center</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn btn-primary">Sign in</button><p>{note}</p></form></main>;return <main className="admin-shell"><aside><a className="admin-brand" href="/">AC <span>Ariem Cinco</span></a><button className={tab==="content"?"active":""} onClick={()=>setTab("content")}><Settings2/>Site content</button><button className={tab==="inquiries"?"active":""} onClick={()=>setTab("inquiries")}><Inbox/>Inquiries</button><button className="signout" onClick={()=>su?.auth.signOut()}><LogOut/>Sign out</button></aside><section className="admin-main"><header><div><p className="kicker">Owner control center</p><h2>{tab==="content"?"Site content":"Engagement requests"}</h2></div><a href="/">View website</a></header>{tab==="content"?<div className="editor-card">{Object.entries(form).map(([k,v])=><label key={k}>{k.replace("_"," ")}<textarea rows={k==="intro"?5:1} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button className="btn btn-primary" onClick={save}><Save size={17}/>Save</button><p>{note}</p></div>:<div className="inquiry-list">{items.map(x=><article key={x.id}><div><span className="status">{x.status}</span><small>{new Date(x.created_at).toLocaleDateString()}</small></div><h3>{x.name}</h3><p>{x.message}</p><a href={`mailto:${x.email}`}>{x.email}</a></article>)}</div>}</section></main>}
const routes:Record<string,React.ReactNode>={'/':<Home/>,'/portfolio':<Portfolio/>,'/foundation':<Foundation/>,'/topics':<Topics/>,'/highlights':<Highlights/>,'/projects':<Projects/>,'/contact':<Contact/>,'/rfq':<RFQ/>,'/schedule':<Schedule/>,'/control-center':<Admin/>};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');createRoot(document.getElementById('root')!).render(routes[location.pathname]??<Home/>);
